### ISSUE TITLE
Event not captured in elements defined inside StaticMap or ReactGLMap

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#1]
<DeckGL
                    initialViewState={{ ...this.state.viewport }}
                    controller={true}
                    layers={[this.state.renderLayer]}
                    onClick={(info, event) => {
                        console.log("info", info);
                        console.log("event", event);
                    }}
                >
                    <StaticMap
                        mapStyle="mapbox://styles/mapbox/dark-v9"
                        mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN} >
                        <button onClick={event => {
                            console.log("hey", event); // This is not logging when click
                        }}>click me</button>
                    </StaticMap>
                </DeckGL>

**Comment by prastut** [comment]
Won't work like this. StaticMap API doesn't support children props. 

Follow this tutorial: http://vis.academy/#/building-a-geospatial-app/2-map-data-overlays-scatterplot

Specifically: 
1. Controls are being rendered here: https://github.com/uber-common/vis-academy/blob/master/src/demos/building-a-geospatial-app/2-scatterplot-overlay/src/app.js#L103-L106 
2. Controls Implementation: https://github.com/uber-common/vis-academy/blob/master/src/demos/building-a-geospatial-app/2-scatterplot-overlay/src/controls.js#L110-L148

**Comment by dhruv10** [comment]
Thank you @prastut

**Comment by dhruv10** [comment]
fixed with commit ca8ad0f86d6aaca1dcf06d7efa490cdd130595a2
