### ISSUE TITLE
FOAMViz Home Page

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#10]
Similar to <img width="1440" alt="Frame (4)" src="https://user-images.githubusercontent.com/10279686/66102556-63b0cc00-e5d0-11e9-8e2e-b4e566553b18.png">

- [x] Home page to house all 3 viz. 
- [x] Each viz on a separate URL.

**Comment by dhruv10** [comment]
Feedback awaited for current HomePage which is live on https://dev-foamviz.surge.sh/#/

**Comment by prastut** [comment]
- [x] Making the page responsive. 
- [x] Taking aesthetic elements from https://polkavizproject.surge.sh/#/
