### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#11]
##### Visualizing Density of Points: 
* Visualization using: Hexagon Layer in deck.gl
* Properties: 
    * Each hexagon shows aggregate number of POI's in that area. 
    * Height of hexagon is proportional to the number of POI's aggregated in that area. 
* On Hover Information: 
    * Specs: 
        * Properties from deck.gl
            * pickable: true
            * autoHighlight: true
        * Properties to be displayed in tooltip:
            * Latitude.
            * Longitude.
            * Number of POI's that are aggregated.
            * Accumulated value of FOAM tokens. 
            * Accumulated value of FOAM tokens in USD. 
            * Cartographers involved.
    * Example: 
        * Latitude: 51.0
        * Longitude: -0.11
        * POI's: 5
        * Accumulated sum of FOAM tokens: 5000
        * Accumulated value of FOAM tokens: $300
        * Cartographers involved: 3

##### Visualizing staked tokens:
* Visualization using: Hexagon Layer in deck.gl 
* Each hexagon height corresponds to the staked POI
* On Hover Information: 
    * Specs: 
        * Properties from deck.gl
            * pickable: true
            * autoHighlight: true
        * Properties to be displayed in tooltip:
            * Latitude.
            * Longitude.
            * FOAM tokens staked.
            * Cartographer details: 
                * Name
                * FOAM.tools link
                * View cartographer journey.
    * Example: 
        * Latitude: 51.0
        * Longitude: -0.11
        * FOAM tokens staked: 50
        * Cartographer: 
            * Alex
            * View on FOAM tools - link
            * View journey - link

**Comment by prastut** [comment]
- [ ] Density of points tooltip

**Comment by prastut** [comment]
Reference: 
1. https://github.com/uber/deck.gl/blob/master/docs/whats-new.md#auto-tooltip
2. https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#gettooltip-function-optional

**Comment by dhruv10** [comment]
Fixed with commit 7068880b3357c445eae37c0edb0963dd5622c8eb

Not done value of FOAM token in USD now. Which API shall I use, coinbase?

**Comment by prastut** [comment]
https://poloniex.com/public?command=returnTicker
To get the price of 1 FOAM token: BTC_FOAM.last* USDC_BTC.last

**Comment by dhruv10** [comment]
Referenced commit 016f6d673632b1f1877b93f763450bc1d1c2fd74

**Comment by dhruv10** [comment]
Everything's done in the tooltip data except cartographer's involved/ details.
Please explain how to calculate this info.

**Comment by prastut** [comment]
> Everything's done in the tooltip data except cartographer's involved/ details.

Not high priority at the moment.
