### ISSUE TITLE
Styling of hexagon layer

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#2]
- [x]  Add lighting in hexagon layers as given in https://deck.gl/#/examples/core-layers/hexagon-layer. Use Phong shading, ambient light techniques given in https://github.com/uber/deck.gl/blob/7.3-release/examples/website/3d-heatmap/app.js

- [x]  Load the hexagon layer tower in an animated way like constructing them from the ground to upwards

**Comment by prastut** [comment]
- [ ] Map color has to become blue as well. Compare [deck.gl example's background map color]( https://deck.gl/#/examples/core-layers/hexagon-layer) with http://foamviz.surge.sh/

**Comment by dhruv10** [comment]
There's no difference in the map style. Both are using dark-v9
And, techniques like lighting and shading are already implemented as given in UK road accidents example https://github.com/uber/deck.gl/blob/7.3-release/examples/website/3d-heatmap/app.js

**Comment by prastut** [comment]
![image](https://user-images.githubusercontent.com/10279686/66703246-1f3ed200-ed2e-11e9-86f5-960e4188504a.png)
![image](https://user-images.githubusercontent.com/10279686/66703253-2fef4800-ed2e-11e9-888b-58716336eb1d.png)

Aren't both of these colors different? If yes, then something needs to be fixed.

**Comment by dhruv10** [comment]
Let's get into it as soon as other priority stuff is fixed

**Comment by dhruv10** [comment]
Figured this out. This is a custom style on map https://github.com/dbabbs/flight-map/blob/master/styles/xyz-osm-dark.json

**Comment by dhruv10** [comment]
> Map color has to become blue as well. Compare deck.gl example's background map color with http://foamviz.surge.sh/

Referencing issue #80
