### ISSUE TITLE
UI / UX changes in control panel

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#3]
- [x]  Changing UI of the control panel according to Figma designs

- [x]  Add a legend

**Comment by prastut** [comment]
Link for easy access: https://www.figma.com/file/wgwdWyG4JJa2LaqWP5uD22/Visualizing-the-FOAM-Map's-Data?node-id=53%3A20

**Comment by dhruv10** [comment]
Fixed by commit 9ae8e7d95c6fc7c525a6afca6e8f5c39611224ff

**Comment by prastut** [comment]
![image](https://user-images.githubusercontent.com/10279686/66694210-a4929a00-ecce-11e9-81c6-1546e9ede63b.png)

Short term fixes: 
- [x] Currently, the control panel runs to the bottom of the screen which arises from https://github.com/prastut/foamviz/blob/dev/src/components/controls.js#L210. Need to be a small concise control panel. 
- [x] Remove the "Dark V9" option present on the top left and move the control panel above. 

Long term fixes: 
- [ ] UX fixes. Currently, the panel is confusing to a user. Compare this to https://flightmapper.io/maps/pdebree and people get context of what they are looking at. Will drop specific feedback to brainstorm together on.

**Comment by dhruv10** [comment]
- Fixed short term changes with commit 4b29f3a9fae50bee616713964f06f1d6b5858cd8
- Let's brainstorm over long term UX changes

**Comment by prastut** [comment]
- [x] top: 5vh. Panel should start from top left corner of the screen. 

Options specific fixes: 
- [x] Underline the option which is selected. 
- [x] curser:pointer on the options. https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by dhruv10** [comment]
Fixed with commit a97134138ca3efd1cc197170def12c646db9b18f
