### ISSUE TITLE
Density of Points + Staked POI's - UX for finding places

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#31]
https://hoodmaps.com/delhi-neighborhood-map

**Comment by prastut** [comment]
- [ ] Inspiration from Google Maps for side panel interactions
- [x] Load user's location. 
- [x] Mobile optimization (Google maps)

**Comment by dhruv10** [comment]
Can you please explain
> Inspiration from Google Maps for side panel interactions

Is it anything apart from referring to take ideas while making it mobile responsive?

**Comment by prastut** [comment]
@dhruv10, unfortunately, I don't remember what I meant by side panel interactions. Let's address this as we solve mobile responsive issues.
