### ISSUE TITLE
Finding an optimal method of fetching data for density of points & staked tokens

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#4]
Two approaches are to fetch data points residing inside 2x of the user's viewport OR fetching the entire world's data all at once. Need to test performance and rendering time in both these cases.

**Comment by dhruv10** [comment]
I have tested two methods, the average result fo multiple tests are:
1. Fetching the entire USA's data using a large bbox
    - Inital DOMContentLoad time: 1.4s
    - Finish loading content: 20s

2. Fetching only NYC's data (ie. User's current viewport)
    - Inital DOMContentLoad time: 1.2s
    - Finish loading content: 3s 

I think we should capture the user's viewport, multiply it two times and fetch data accordingly. What's your take @prastut ?

**Comment by prastut** [comment]
> I think we should capture the user's viewport, multiply it two times and fetch data accordingly.

This makes sense. Execute this.

**Comment by prastut** [comment]
For reference, use this callback which get's fired every time user changes the viewport to fetch data accordingly https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#onviewstatechange-function

**Comment by dhruv10** [comment]
On it, thanks for the reference.

**Comment by dhruv10** [comment]
I can't find a function/library that doubles the bounding box. Alternatively, I found a way to calculate bounding box around lat, long with a given distance in meters (for ref - 
https://stackoverflow.com/questions/3144044/calculating-the-bounding-box-using-javascript)
but It has some practical issues as if the user's viewport is too large to occupy the entire USA etc.

This can work but let me know if you have some better approach/insights OR I'll research more into this matter.

**Comment by prastut** [comment]
> but It has some practical issues as if the user's viewport is too large to occupy the entire USA etc.

Yup. It doesn't make sense principally then. Good catch. 

I think for now let's fetch only the bounding box data (and not 2x of it). And see how the interaction works on the viz when user pans and the data loads.

**Comment by dhruv10** [comment]
Fixed with commit 708272be54bf1ab40746e26277f20034656d5671

**Comment by dhruv10** [comment]
But the data loads for every single time the viewport is changed. Shouldn't we need to fetch and render data only if the map is stopped after changing the viewport (after user drags) ?

**Comment by prastut** [comment]
@dhruv10 https://github.com/uber/deck.gl/blob/master/docs/whats-new.md#new-interaction-callbacks 

`dragEnd` happens then fetchData?

**Comment by dhruv10** [comment]
Yes, this should be the right way otherwise multiple requests get in the call stack and data is fetched multiple times and rendered multiple times. I'll update this asap.

**Comment by prastut** [comment]
Performance recommendations: https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md

**Comment by prastut** [comment]
- [ ] Only show animation for points that are newly fetched. Currently it happens for every point, even if it's drawn on the screen. 
- [ ] It seems that the elevation scale get's optimized after the animation takes place for I see new points emerge -> animate to a tall height -> and then get shorter. Need to fix this. Probably by either capping the maximum elevation.

**Comment by dhruv10** [comment]
> Only show animation for points that are newly fetched. Currently, it happens for every point, even if it's drawn on the screen.

I think this can be achieved by [performance_optimization](https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md) you had sent in the comment above.

>  It seems that the elevation scale gets optimized after the animation takes place for I see new points emerge -> animate to a tall height -> and then get shorter. Need to fix this. Probably by either capping the maximum elevation.

I'll try by setting a maximum elevation level.

**Comment by prastut** [comment]
Extreme performanc optimization principle: https://twitter.com/flcnhvy/status/1186885012811079680?s=20

**Comment by prastut** [comment]
https://github.com/uber/deck.gl/issues/936

**Comment by dhruv10** [comment]
Initially, we thought of this as a performance issue but it was a precision issue caused by internal functioning of deck.gl - how it renders layers on the screen
Follow this [issue](https://github.com/prastut/foamviz/issues/44) to know more details
