### ISSUE TITLE
Rendering data according to stake value in Staked Point visualization

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#5]
- [x]  Add option in control panel to switch views between Density of Points & Staked Tokens 

 - [x]  Make changes to render the hexagon layer according to staked points value

**Comment by prastut** [comment]
There is a lot of chatter on Github issues and it seems that people may have found solution for it: 
1. https://github.com/uber/deck.gl/issues/2527
2. https://github.com/uber/deck.gl/issues/829
3. https://github.com/uber/deck.gl/issues/1852

Be vary of the dates when these issues were created/replied to and hence take the latest information into account.

**Comment by dhruv10** [comment]
Fixed with commit 2401783d4b5191b9f4e3844b62dfc8ed227f6a89
