### ISSUE TITLE
Becoming demo ready for Wednesday

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#55]
## **Live** demo ready for Wednesday expectations: 
1. Viz 1 working with panning and zooming and fetching new data. 
2. Viz 2 working and UX similar to flight mapper. 

Days: 
Monday - today
Tuesday
Wednesday

Timeline broken into 2 parts: 
1. Execution timeline
2. Testing timeline - buffer of 1 day (i.e Wednesday)

Days remaining for step 1: 
Monday
Tuesday

## Fixes in Viz 1
HIGH PRIORITY
- [x] Merge PR by cleaning code in the PR, into the main codebase. Deploying it live. @dhruv10 ideally like you to do it so that you are aware of what fixes I did to ensure you get to know how I fixed it. Let me know if you are unable to deliver this by being aware of timelines, and I will take over. 

## Fixes in Viz 2
HIGH PRIORITY
- [x] Initial viewport config
- [x] Custom error box
- [x] Correction of API data
- [x] Rendering arc layer with different colors

MEDIUM PRIORITY
- [x] Remove white area by repeating base color
- [x] UI improvements in Profile panel (lower width, font-fixes etc.)
- [x] Width of arc layer
- [x] Coloring of time-series panel
- [x] Loader while fetching data
- [x] Map 2D to 3D switch button
- [x] Profile Panel: height of panel, padding, change map view buttons height, color, margin between data
- [x] Time-series panel: play button css, position of time series panel like flightmapper, make the slider smooth
- [x] Adjust viewport acc to data on initial view load
- [x] Add scatter plot layer
- [ ] hexagon bins in time-series using d3

### Common fixes in Viz 1 and Viz 2
MEDIUM PRIORITY
- [ ] Changing base map tile to OSM dark
- [x] A pleasing loading state...
- [x] Title bar to be dynamic
- [x] favicon to be changed
- [x] FOAM title in viz's panel

## Mapping fixes with the timeline: 
Monday - High Priority.
Tuesday - Medium Priority. 
Wednesday - Testing

**Comment by prastut** [comment]
- [x] Remove white area by repeating base color

![image](https://user-images.githubusercontent.com/10279686/68967327-eea6f800-0805-11ea-9305-fefceb7e543e.png)

**Comment by dhruv10** [comment]
Todo
> 1. hexagon bins in time-series using d3

Is not relevant now as we have single data point now instead of data by date

> 2. Changing base map tile to OSM dark

Moving this to common issues #80
