### ISSUE TITLE
"Make it fast, make it smooth"

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#75]
Performance optimization in all the three visualizations. 

Ideal: 
![image](https://user-images.githubusercontent.com/10279686/70322905-67233680-1851-11ea-93fc-acbc11e3a7ec.png)
From: https://firstround.com/review/how-superhuman-built-an-engine-to-find-product-market-fit/

Tools: 
https://developers.google.com/web/tools/chrome-devtools/evaluate-performance

Todo List: 

Speculation that these would have compounding effects: 
- [x] API optimizations. 
   - [x] Thinking from a global state that is funneling data to all the three visualizations. For eg: we fetch all the points for viz3, that solves viz1 all points + viz2 some of the cartographer points. Should we start fetching all data on the home page itself? or make an external server that updates every 10 minutes to fetch live data from FOAM and we use this server for our visualizations. 

- [x] Storing fetched data in a cache.

**Comment by dhruv10** [comment]
Referencing issue #76
