### ISSUE TITLE
Common Issues in all visualizations

### ISSUE THREAD

**Issue by dhruv10** [prastut/foamviz#80]
> Prioritizing to solve specific issues over common issues

**Common Issues Todo List**

Medium Priority:

- [x] HomePage issue in #10 

- [x] Adding FOAM navbar

- [x] Mobile Optimization - making it responsive

Good to have features:

- [ ] Using OSM's blue map

**Viz Specific Issues:**

1. VizPOIAnalytics #78 
2. VizCartographerJourney #79 
3. VizDataGlobe #76

**Comment by prastut** [comment]
@dhruv10 what is FOAM navbar?

**Comment by dhruv10** [comment]
> @dhruv10 what is FOAM navbar?

![foamnavbar](https://user-images.githubusercontent.com/32517802/71448834-b16c4900-2767-11ea-801e-b5d9faeabf6e.png)
