### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#85]
![image](https://user-images.githubusercontent.com/10279686/72591821-2d9d1b00-3927-11ea-9741-3ebd339836b9.png)

![image](https://user-images.githubusercontent.com/10279686/72591892-5d4c2300-3927-11ea-814d-b42007754b3f.png)
![image](https://user-images.githubusercontent.com/10279686/72591946-7b198800-3927-11ea-9682-6b7f173b2519.png)

These are from: https://web.dev/measure/

My reaction to above is summarized in this video: https://www.youtube.com/watch?v=umDr0mPuyQc

**Comment by prastut** [comment]
- [ ] Viz3 janky experience

**Comment by dhruv10** [comment]
> * [ ]  Viz3 janky experience

We are using GPU for rendering, that day in-office we got no GPU usage as we were running it locally. But in production apps, WebGL makes sure internally that GPU is used. It is also shown in Chrome's Profile when checked the deployed URL.

**Comment by dhruv10** [comment]
Closed in #93
