### ISSUE TITLE
Reduce loading time

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#87]
For viz 3: 
1. fixing the heroku deployment problem
2. updating foamviz with new server API

For viz 2: 
1. asking FOAM team and Caleb to reduce the loading time of viz2

**Comment by dhruv10** [comment]
Shifted to heroku server in #91

**Comment by dhruv10** [comment]
Integrated Caleb's new API in #103  but we are still not able to get a huge time difference. 
Refer to https://github.com/buidl-labs/foamviz/issues/92#issuecomment-598108822 for further clarity

**Comment by dhruv10** [comment]
#106
