### ISSUE TITLE
Title Bar Changes

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#9]
- [x] Change title from "React App" to "FOAMViz| Density of points"
- [x] Change icon to FOAM's favicon.

**Comment by prastut** [comment]
- [x] Title on https://dev.foamviz.surge.sh/#/data-globe to be: "FOAMViz - Evolution on 🌎"
- [x] Humanize title for viz 1

**Comment by dhruv10** [comment]
> Title on https://dev.foamviz.surge.sh/#/data-globe to be: "FOAMViz - Evolution on 🌎"
 Humanize title for viz 1

Fixed in c61fe47

**Comment by dhruv10** [comment]
#106
