### ISSUE TITLE
Hompage bugfixes list

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#96]
### Problem: 
How to reproduce the issue? Disable cache in chrome. 

The issue is recorded here: 
https://www.loom.com/share/7874b7e0f05f4b8682c70de1dc76ad94

The bottom things load before than the "The FOAMViz project" 

### Potential Solution: 
Take inspiration from: https://www.dharma.io/
See how things gracefully load. "Let the interface come to you"

### Problem: 
Users can't answer what is this project. Questions that come to mind: 
1. What is FOAM? 
2. What is the FOAMViz project? 

Missing elements from above questions: 
1. There is no link/mention of FOAM anywhere. We should deflect traffic to FOAM as well for the curious souls instead of them googling what is FOAM. 
2. There is no "what" that describes what FOAMViz project is. 

### Potential Solution: 
For eg: 
See how Compound explains itself on https://compound.finance/
Using https://codesandbox.io/s/react-text-loop-playground-br4q1 we can add: 

1. Heading: 
"Visualize statistics around POI's"
"Visualize journey of cartographers"
"Visualize the evolution of FOAM on planetary scale"

2. Subheading
FOAMViz is an umbrella project over FOAM TCR's data that encompasses interactive tools to analyze ecosystem activity on FOAM's map. 

Then gracefully land users to all the three visualizations. 

### Problem: 

* Allow the titles of the homepage sections to contain a hyperlink.
  * Currently you need to click on the image to be taken to the page

* Increase the text spacing 
  * Use bulleted rather than number lists

**Comment by prastut** [comment]
Take inspiration from: https://www.dharma.io/

See things gracefully load.

**Comment by prastut** [comment]
I also think there are these missing elements from the homepage: 
1. There is no link to FOAM anywhere. 
2. There is no what that describes what FOAMViz project is. 

### Scribbles: 
For eg: https://compound.finance/
Using https://codesandbox.io/s/react-text-loop-playground-br4q1 we can add: 

1. Heading: 
"Visualize statistics around POI's"
"Visualize journey of cartographers"
"Visualize the evolution of FOAM on planetary scale"

2. Subheading
FOAMViz is an umbrella project over FOAM TCR's data that encompasses interactive tools to analyze ecosystem activity on FOAM's map. 

Then gracefully land users to all the three visualizations.

**Comment by dhruv10** [comment]
Condensed fixes list:

1. Need a new design addressing the above-stated issues like What is FOAM? etc.
2. Bullet list alignment
3. Footer content with buidl-labs and GitHub repository link
4. Include a `Get Started` button for every viz

**Comment by dhruv10** [comment]
#106
