### ISSUE TITLE
Viz 3 UX Fixes

### ISSUE THREAD

**Issue by prastut** [prastut/foamviz#99]
### Subheading Fixes: 

- [x] Net Value Staked to "Net value of FOAM tokens staked" 
- [x] FOAM Tokens Staked subheading change to "Total FOAM tokens staked on the planet"

Should we also reverse the order? First total FOAM tokens staked -> then their value in USD? 

### Tooltip Fixes
Make them more informative + order changes. 

First I would like to know number of points in a particular bar (eg: x points staked)
Then I would like to know amount staked in this particular bar. (eg: `x*y `where y = sum of each point's staked amount))
Then I would like to know USD value of total points staked in this particular bar. (eg: `x*y*z` where z = FOAM's exchange rate in USD)

**Comment by dhruv10** [comment]
@prastut could you please quote the difference between
> First I would like to know total points in a particular bar.
&
> Then I would like to know total points staked in this particular bar. ?

**Comment by dhruv10** [comment]
> Should we also reverse the order? First total FOAM tokens staked -> then their value in USD?

People are usually more interested in $, so I put that first. I have changed the order now as it makes more sense to you.

**Comment by dhruv10** [comment]
Fixed in #102

**Comment by prastut** [comment]
> @prastut could you please quote the difference between
> 
> > First I would like to know total points in a particular bar.
> > &
> > Then I would like to know total points staked in this particular bar. ?

@dhruv10 edited comment for clarity.

**Comment by dhruv10** [comment]
Fixed in #106 a9cc8d2
